spring.application.name=FIC Portal
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:${MONGODB_URI:mongodb://localhost:27017/fic_portal}}

spring.thymeleaf.cache=false
server.servlet.session.timeout=45m

fic.quiz.duration-minutes=30
